//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  fuelPrices: FuelPrices;
  fuelPricesConnection: FuelPricesConnection;
  location: Location;
  locationConnection: LocationConnection;
  siteAlert: SiteAlert;
  siteAlertConnection: SiteAlertConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFuelPricesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFuelPricesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FuelPricesFilter>;
};


export type QueryLocationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLocationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocationFilter>;
};


export type QuerySiteAlertArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteAlertConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteAlertFilter>;
};

export type DocumentFilter = {
  fuelPrices?: InputMaybe<FuelPricesFilter>;
  location?: InputMaybe<LocationFilter>;
  siteAlert?: InputMaybe<SiteAlertFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = FuelPrices | Location | SiteAlert | Folder;

export type FuelPricesLocationsExit_260 = {
  __typename?: 'FuelPricesLocationsExit_260';
  regular?: Maybe<Scalars['Float']['output']>;
  diesel?: Maybe<Scalars['Float']['output']>;
  updated?: Maybe<Scalars['String']['output']>;
};

export type FuelPricesLocationsMini_Mart = {
  __typename?: 'FuelPricesLocationsMini_mart';
  regular?: Maybe<Scalars['Float']['output']>;
  diesel?: Maybe<Scalars['Float']['output']>;
  updated?: Maybe<Scalars['String']['output']>;
};

export type FuelPricesLocationsFishermans_Cove = {
  __typename?: 'FuelPricesLocationsFishermans_cove';
  regular?: Maybe<Scalars['Float']['output']>;
  diesel?: Maybe<Scalars['Float']['output']>;
  updated?: Maybe<Scalars['String']['output']>;
};

export type FuelPricesLocations = {
  __typename?: 'FuelPricesLocations';
  exit_260?: Maybe<FuelPricesLocationsExit_260>;
  mini_mart?: Maybe<FuelPricesLocationsMini_Mart>;
  fishermans_cove?: Maybe<FuelPricesLocationsFishermans_Cove>;
};

export type FuelPricesTruckStop = {
  __typename?: 'FuelPricesTruckStop';
  diesel?: Maybe<Scalars['Float']['output']>;
  def?: Maybe<Scalars['Float']['output']>;
  updated?: Maybe<Scalars['String']['output']>;
};

export type FuelPrices = Node & Document & {
  __typename?: 'FuelPrices';
  linkLocations?: Maybe<Scalars['Boolean']['output']>;
  locations?: Maybe<FuelPricesLocations>;
  truckStop?: Maybe<FuelPricesTruckStop>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type FuelPricesLocationsExit_260Filter = {
  regular?: InputMaybe<NumberFilter>;
  diesel?: InputMaybe<NumberFilter>;
  updated?: InputMaybe<StringFilter>;
};

export type FuelPricesLocationsMini_MartFilter = {
  regular?: InputMaybe<NumberFilter>;
  diesel?: InputMaybe<NumberFilter>;
  updated?: InputMaybe<StringFilter>;
};

export type FuelPricesLocationsFishermans_CoveFilter = {
  regular?: InputMaybe<NumberFilter>;
  diesel?: InputMaybe<NumberFilter>;
  updated?: InputMaybe<StringFilter>;
};

export type FuelPricesLocationsFilter = {
  exit_260?: InputMaybe<FuelPricesLocationsExit_260Filter>;
  mini_mart?: InputMaybe<FuelPricesLocationsMini_MartFilter>;
  fishermans_cove?: InputMaybe<FuelPricesLocationsFishermans_CoveFilter>;
};

export type FuelPricesTruckStopFilter = {
  diesel?: InputMaybe<NumberFilter>;
  def?: InputMaybe<NumberFilter>;
  updated?: InputMaybe<StringFilter>;
};

export type FuelPricesFilter = {
  linkLocations?: InputMaybe<BooleanFilter>;
  locations?: InputMaybe<FuelPricesLocationsFilter>;
  truckStop?: InputMaybe<FuelPricesTruckStopFilter>;
};

export type FuelPricesConnectionEdges = {
  __typename?: 'FuelPricesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<FuelPrices>;
};

export type FuelPricesConnection = Connection & {
  __typename?: 'FuelPricesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FuelPricesConnectionEdges>>>;
};

export type LocationTruckStop = {
  __typename?: 'LocationTruckStop';
  phone?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
  amenities?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Location = Node & Document & {
  __typename?: 'Location';
  order?: Maybe<Scalars['Float']['output']>;
  name: Scalars['String']['output'];
  navLabel: Scalars['String']['output'];
  shortLabel?: Maybe<Scalars['String']['output']>;
  aka?: Maybe<Scalars['String']['output']>;
  address: Scalars['String']['output'];
  city?: Maybe<Scalars['String']['output']>;
  state?: Maybe<Scalars['String']['output']>;
  zip?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  phoneLabel?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
  cardLine?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  amenities?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  truckStop?: Maybe<LocationTruckStop>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LocationTruckStopFilter = {
  phone?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
  amenities?: InputMaybe<StringFilter>;
};

export type LocationFilter = {
  order?: InputMaybe<NumberFilter>;
  name?: InputMaybe<StringFilter>;
  navLabel?: InputMaybe<StringFilter>;
  shortLabel?: InputMaybe<StringFilter>;
  aka?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  city?: InputMaybe<StringFilter>;
  state?: InputMaybe<StringFilter>;
  zip?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  phoneLabel?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
  cardLine?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  amenities?: InputMaybe<StringFilter>;
  truckStop?: InputMaybe<LocationTruckStopFilter>;
};

export type LocationConnectionEdges = {
  __typename?: 'LocationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Location>;
};

export type LocationConnection = Connection & {
  __typename?: 'LocationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LocationConnectionEdges>>>;
};

export type SiteAlert = Node & Document & {
  __typename?: 'SiteAlert';
  active?: Maybe<Scalars['Boolean']['output']>;
  message?: Maybe<Scalars['String']['output']>;
  linkLabel?: Maybe<Scalars['String']['output']>;
  linkHref?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteAlertFilter = {
  active?: InputMaybe<BooleanFilter>;
  message?: InputMaybe<StringFilter>;
  linkLabel?: InputMaybe<StringFilter>;
  linkHref?: InputMaybe<StringFilter>;
};

export type SiteAlertConnectionEdges = {
  __typename?: 'SiteAlertConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteAlert>;
};

export type SiteAlertConnection = Connection & {
  __typename?: 'SiteAlertConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteAlertConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateFuelPrices: FuelPrices;
  createFuelPrices: FuelPrices;
  updateLocation: Location;
  createLocation: Location;
  updateSiteAlert: SiteAlert;
  createSiteAlert: SiteAlert;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateFuelPricesArgs = {
  relativePath: Scalars['String']['input'];
  params: FuelPricesMutation;
};


export type MutationCreateFuelPricesArgs = {
  relativePath: Scalars['String']['input'];
  params: FuelPricesMutation;
};


export type MutationUpdateLocationArgs = {
  relativePath: Scalars['String']['input'];
  params: LocationMutation;
};


export type MutationCreateLocationArgs = {
  relativePath: Scalars['String']['input'];
  params: LocationMutation;
};


export type MutationUpdateSiteAlertArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteAlertMutation;
};


export type MutationCreateSiteAlertArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteAlertMutation;
};

export type DocumentUpdateMutation = {
  fuelPrices?: InputMaybe<FuelPricesMutation>;
  location?: InputMaybe<LocationMutation>;
  siteAlert?: InputMaybe<SiteAlertMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  fuelPrices?: InputMaybe<FuelPricesMutation>;
  location?: InputMaybe<LocationMutation>;
  siteAlert?: InputMaybe<SiteAlertMutation>;
};

export type FuelPricesLocationsExit_260Mutation = {
  regular?: InputMaybe<Scalars['Float']['input']>;
  diesel?: InputMaybe<Scalars['Float']['input']>;
  updated?: InputMaybe<Scalars['String']['input']>;
};

export type FuelPricesLocationsMini_MartMutation = {
  regular?: InputMaybe<Scalars['Float']['input']>;
  diesel?: InputMaybe<Scalars['Float']['input']>;
  updated?: InputMaybe<Scalars['String']['input']>;
};

export type FuelPricesLocationsFishermans_CoveMutation = {
  regular?: InputMaybe<Scalars['Float']['input']>;
  diesel?: InputMaybe<Scalars['Float']['input']>;
  updated?: InputMaybe<Scalars['String']['input']>;
};

export type FuelPricesLocationsMutation = {
  exit_260?: InputMaybe<FuelPricesLocationsExit_260Mutation>;
  mini_mart?: InputMaybe<FuelPricesLocationsMini_MartMutation>;
  fishermans_cove?: InputMaybe<FuelPricesLocationsFishermans_CoveMutation>;
};

export type FuelPricesTruckStopMutation = {
  diesel?: InputMaybe<Scalars['Float']['input']>;
  def?: InputMaybe<Scalars['Float']['input']>;
  updated?: InputMaybe<Scalars['String']['input']>;
};

export type FuelPricesMutation = {
  linkLocations?: InputMaybe<Scalars['Boolean']['input']>;
  locations?: InputMaybe<FuelPricesLocationsMutation>;
  truckStop?: InputMaybe<FuelPricesTruckStopMutation>;
};

export type LocationTruckStopMutation = {
  phone?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
  amenities?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type LocationMutation = {
  order?: InputMaybe<Scalars['Float']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  navLabel?: InputMaybe<Scalars['String']['input']>;
  shortLabel?: InputMaybe<Scalars['String']['input']>;
  aka?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  city?: InputMaybe<Scalars['String']['input']>;
  state?: InputMaybe<Scalars['String']['input']>;
  zip?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  phoneLabel?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
  cardLine?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  amenities?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  truckStop?: InputMaybe<LocationTruckStopMutation>;
};

export type SiteAlertMutation = {
  active?: InputMaybe<Scalars['Boolean']['input']>;
  message?: InputMaybe<Scalars['String']['input']>;
  linkLabel?: InputMaybe<Scalars['String']['input']>;
  linkHref?: InputMaybe<Scalars['String']['input']>;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type FuelPricesLocationsExit_260Filter = {
  regular?: NumberFilter | null | undefined;
  diesel?: NumberFilter | null | undefined;
  updated?: StringFilter | null | undefined;
};

export type FuelPricesLocationsMini_MartFilter = {
  regular?: NumberFilter | null | undefined;
  diesel?: NumberFilter | null | undefined;
  updated?: StringFilter | null | undefined;
};

export type FuelPricesLocationsFishermans_CoveFilter = {
  regular?: NumberFilter | null | undefined;
  diesel?: NumberFilter | null | undefined;
  updated?: StringFilter | null | undefined;
};

export type FuelPricesLocationsFilter = {
  exit_260?: FuelPricesLocationsExit_260Filter | null | undefined;
  mini_mart?: FuelPricesLocationsMini_MartFilter | null | undefined;
  fishermans_cove?: FuelPricesLocationsFishermans_CoveFilter | null | undefined;
};

export type FuelPricesTruckStopFilter = {
  diesel?: NumberFilter | null | undefined;
  def?: NumberFilter | null | undefined;
  updated?: StringFilter | null | undefined;
};

export type FuelPricesFilter = {
  linkLocations?: BooleanFilter | null | undefined;
  locations?: FuelPricesLocationsFilter | null | undefined;
  truckStop?: FuelPricesTruckStopFilter | null | undefined;
};

export type LocationTruckStopFilter = {
  phone?: StringFilter | null | undefined;
  hours?: StringFilter | null | undefined;
  amenities?: StringFilter | null | undefined;
};

export type LocationFilter = {
  order?: NumberFilter | null | undefined;
  name?: StringFilter | null | undefined;
  navLabel?: StringFilter | null | undefined;
  shortLabel?: StringFilter | null | undefined;
  aka?: StringFilter | null | undefined;
  address?: StringFilter | null | undefined;
  city?: StringFilter | null | undefined;
  state?: StringFilter | null | undefined;
  zip?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  phoneLabel?: StringFilter | null | undefined;
  hours?: StringFilter | null | undefined;
  cardLine?: StringFilter | null | undefined;
  intro?: StringFilter | null | undefined;
  amenities?: StringFilter | null | undefined;
  truckStop?: LocationTruckStopFilter | null | undefined;
};

export type SiteAlertFilter = {
  active?: BooleanFilter | null | undefined;
  message?: StringFilter | null | undefined;
  linkLabel?: StringFilter | null | undefined;
  linkHref?: StringFilter | null | undefined;
};

export type FuelPricesPartsFragment = { __typename: 'FuelPrices', linkLocations: boolean | null, locations: { __typename: 'FuelPricesLocations', exit_260: { __typename: 'FuelPricesLocationsExit_260', regular: number | null, diesel: number | null, updated: string | null } | null, mini_mart: { __typename: 'FuelPricesLocationsMini_mart', regular: number | null, diesel: number | null, updated: string | null } | null, fishermans_cove: { __typename: 'FuelPricesLocationsFishermans_cove', regular: number | null, diesel: number | null, updated: string | null } | null } | null, truckStop: { __typename: 'FuelPricesTruckStop', diesel: number | null, def: number | null, updated: string | null } | null };

export type LocationPartsFragment = { __typename: 'Location', order: number | null, name: string, navLabel: string, shortLabel: string | null, aka: string | null, address: string, city: string | null, state: string | null, zip: string | null, phone: string | null, phoneLabel: string | null, hours: string | null, cardLine: string | null, intro: string | null, amenities: Array<string | null> | null, truckStop: { __typename: 'LocationTruckStop', phone: string | null, hours: string | null, amenities: Array<string | null> | null } | null };

export type SiteAlertPartsFragment = { __typename: 'SiteAlert', active: boolean | null, message: string | null, linkLabel: string | null, linkHref: string | null };

export type FuelPricesQueryVariables = Exact<{
  relativePath: string;
}>;


export type FuelPricesQuery = { fuelPrices: { __typename: 'FuelPrices', id: string, linkLocations: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, locations: { __typename: 'FuelPricesLocations', exit_260: { __typename: 'FuelPricesLocationsExit_260', regular: number | null, diesel: number | null, updated: string | null } | null, mini_mart: { __typename: 'FuelPricesLocationsMini_mart', regular: number | null, diesel: number | null, updated: string | null } | null, fishermans_cove: { __typename: 'FuelPricesLocationsFishermans_cove', regular: number | null, diesel: number | null, updated: string | null } | null } | null, truckStop: { __typename: 'FuelPricesTruckStop', diesel: number | null, def: number | null, updated: string | null } | null } };

export type FuelPricesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: FuelPricesFilter | null | undefined;
}>;


export type FuelPricesConnectionQuery = { fuelPricesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'FuelPrices', id: string, linkLocations: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, locations: { __typename: 'FuelPricesLocations', exit_260: { __typename: 'FuelPricesLocationsExit_260', regular: number | null, diesel: number | null, updated: string | null } | null, mini_mart: { __typename: 'FuelPricesLocationsMini_mart', regular: number | null, diesel: number | null, updated: string | null } | null, fishermans_cove: { __typename: 'FuelPricesLocationsFishermans_cove', regular: number | null, diesel: number | null, updated: string | null } | null } | null, truckStop: { __typename: 'FuelPricesTruckStop', diesel: number | null, def: number | null, updated: string | null } | null } | null } | null> | null } };

export type LocationQueryVariables = Exact<{
  relativePath: string;
}>;


export type LocationQuery = { location: { __typename: 'Location', id: string, order: number | null, name: string, navLabel: string, shortLabel: string | null, aka: string | null, address: string, city: string | null, state: string | null, zip: string | null, phone: string | null, phoneLabel: string | null, hours: string | null, cardLine: string | null, intro: string | null, amenities: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, truckStop: { __typename: 'LocationTruckStop', phone: string | null, hours: string | null, amenities: Array<string | null> | null } | null } };

export type LocationConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: LocationFilter | null | undefined;
}>;


export type LocationConnectionQuery = { locationConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Location', id: string, order: number | null, name: string, navLabel: string, shortLabel: string | null, aka: string | null, address: string, city: string | null, state: string | null, zip: string | null, phone: string | null, phoneLabel: string | null, hours: string | null, cardLine: string | null, intro: string | null, amenities: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, truckStop: { __typename: 'LocationTruckStop', phone: string | null, hours: string | null, amenities: Array<string | null> | null } | null } | null } | null> | null } };

export type SiteAlertQueryVariables = Exact<{
  relativePath: string;
}>;


export type SiteAlertQuery = { siteAlert: { __typename: 'SiteAlert', id: string, active: boolean | null, message: string | null, linkLabel: string | null, linkHref: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteAlertConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: SiteAlertFilter | null | undefined;
}>;


export type SiteAlertConnectionQuery = { siteAlertConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'SiteAlert', id: string, active: boolean | null, message: string | null, linkLabel: string | null, linkHref: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const FuelPricesPartsFragmentDoc = gql`
    fragment FuelPricesParts on FuelPrices {
  __typename
  linkLocations
  locations {
    __typename
    exit_260 {
      __typename
      regular
      diesel
      updated
    }
    mini_mart {
      __typename
      regular
      diesel
      updated
    }
    fishermans_cove {
      __typename
      regular
      diesel
      updated
    }
  }
  truckStop {
    __typename
    diesel
    def
    updated
  }
}
    `;
export const LocationPartsFragmentDoc = gql`
    fragment LocationParts on Location {
  __typename
  order
  name
  navLabel
  shortLabel
  aka
  address
  city
  state
  zip
  phone
  phoneLabel
  hours
  cardLine
  intro
  amenities
  truckStop {
    __typename
    phone
    hours
    amenities
  }
}
    `;
export const SiteAlertPartsFragmentDoc = gql`
    fragment SiteAlertParts on SiteAlert {
  __typename
  active
  message
  linkLabel
  linkHref
}
    `;
export const FuelPricesDocument = gql`
    query fuelPrices($relativePath: String!) {
  fuelPrices(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FuelPricesParts
  }
}
    ${FuelPricesPartsFragmentDoc}`;
export const FuelPricesConnectionDocument = gql`
    query fuelPricesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FuelPricesFilter) {
  fuelPricesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FuelPricesParts
      }
    }
  }
}
    ${FuelPricesPartsFragmentDoc}`;
export const LocationDocument = gql`
    query location($relativePath: String!) {
  location(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LocationParts
  }
}
    ${LocationPartsFragmentDoc}`;
export const LocationConnectionDocument = gql`
    query locationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LocationFilter) {
  locationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LocationParts
      }
    }
  }
}
    ${LocationPartsFragmentDoc}`;
export const SiteAlertDocument = gql`
    query siteAlert($relativePath: String!) {
  siteAlert(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteAlertParts
  }
}
    ${SiteAlertPartsFragmentDoc}`;
export const SiteAlertConnectionDocument = gql`
    query siteAlertConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteAlertFilter) {
  siteAlertConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteAlertParts
      }
    }
  }
}
    ${SiteAlertPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      fuelPrices(variables: FuelPricesQueryVariables, options?: C): Promise<{data: FuelPricesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FuelPricesQueryVariables, query: string}> {
        return requester<{data: FuelPricesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FuelPricesQueryVariables, query: string}, FuelPricesQueryVariables>(FuelPricesDocument, variables, options);
      },
    fuelPricesConnection(variables?: FuelPricesConnectionQueryVariables, options?: C): Promise<{data: FuelPricesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FuelPricesConnectionQueryVariables, query: string}> {
        return requester<{data: FuelPricesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FuelPricesConnectionQueryVariables, query: string}, FuelPricesConnectionQueryVariables>(FuelPricesConnectionDocument, variables, options);
      },
    location(variables: LocationQueryVariables, options?: C): Promise<{data: LocationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationQueryVariables, query: string}> {
        return requester<{data: LocationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationQueryVariables, query: string}, LocationQueryVariables>(LocationDocument, variables, options);
      },
    locationConnection(variables?: LocationConnectionQueryVariables, options?: C): Promise<{data: LocationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationConnectionQueryVariables, query: string}> {
        return requester<{data: LocationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationConnectionQueryVariables, query: string}, LocationConnectionQueryVariables>(LocationConnectionDocument, variables, options);
      },
    siteAlert(variables: SiteAlertQueryVariables, options?: C): Promise<{data: SiteAlertQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteAlertQueryVariables, query: string}> {
        return requester<{data: SiteAlertQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteAlertQueryVariables, query: string}, SiteAlertQueryVariables>(SiteAlertDocument, variables, options);
      },
    siteAlertConnection(variables?: SiteAlertConnectionQueryVariables, options?: C): Promise<{data: SiteAlertConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteAlertConnectionQueryVariables, query: string}> {
        return requester<{data: SiteAlertConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteAlertConnectionQueryVariables, query: string}, SiteAlertConnectionQueryVariables>(SiteAlertConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  